syntax enable
set termguicolors
set guifont=ProFontWindows\ Nerd\ Font\ Mono:h16

set title
set hidden
set number
set cursorline

" tabs and spaces
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set ruler
filetype plugin indent on
autocmd FileType go setlocal noexpandtab shiftwidth=4 softtabstop=4 tabstop=4 shiftwidth=4

" nerdcommenter
let g:NERDSpaceDelims = 1
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

" don't jump to start-of-line on buffer change
set nostartofline
set colorcolumn=100

map <F4>   :call NextColorScheme()<CR>

set mouse=r

set signcolumn=number

" remap 'mark' to gm
nnoremap gm m

let g:go_fmt_command = "golines"
let g:go_fmt_options = {'golines': '-m 100' }

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

iabbrev iferr if err != nil { return err }

